[theme]
primaryColor = "#fcd34d"
backgroundColor = "#030712"
secondaryBackgroundColor = "#111827"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
